export const LOGIN_LOGIN_MAIN = 'LOGIN_LOGIN_MAIN';
export const LOGIN_LOGIN_SUBMIT = 'LOGIN_LOGIN_SUBMIT';
export const LOGIN_REGIST_USER = 'LOGIN_REGIST_USER';
export const LOGIN_CHECK_USER = 'LOGIN_CHECK_USER';